name: camplifytest
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  # --- DEPENDENCIES APLIKASI (Pindah ke sini) ---
  # Wajib ada di sini agar fitur upload foto jalan di APK Release
  image_picker: ^1.0.4
  dotted_border: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
  # --- GENERATOR ICON (Hanya untuk develop) ---
  flutter_launcher_icons: ^0.13.1

# --- KONFIGURASI ICON APLIKASI ---
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/camplify2.png" # Pastikan nama file gambarmu benar ini
  min_sdk_android: 21
  # adaptive_icon_background: "#FFFFFF" # (Opsional) Jika ingin background putih

flutter:
  uses-material-design: true

  # Pastikan folder 'assets' dan subfolder 'images' sudah dibuat di root project
  assets:
    - assets/images/